- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/packages.config
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/RazorEngineReferenceResolver.cs
- src/Cake.Issues.Reporting.Generic/packages.config
Build against Cake 0.26 and Cake.Issues 0.2.0
Also updates XUnit to 2.3.1 and Shouldly to 3.0.0
Fixes #8
Fixes #10
> Update to Cake.Issues 0.2.0

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/GenericIssueReportGeneratorTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/packages.config
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/packages.config
Update to Cake.Issues 0.3.0
Fixes #19
> (GH-19) Update to Cake.Issues 0.3.0

- src/Cake.Issues.Reporting.Generic/Templates/Diagnostic.cshtml
Update diagnostic template with new fields
> Update diagnostic template with new fields

- src/Cake.Issues.Reporting.Generic.Tests/GenericIssueReportFixture.cs
- src/Cake.Issues.Reporting.Generic.Tests/GenericIssueReportGeneratorTests.cs
Add test cases for checking if embedded templates can be compiled.
> Add test cases for all embedded templates

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/GenericIssueReportGeneratorTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/packages.config
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/packages.config
Build against Cake 0.28.0
Fixes #27
> (GH-27) Build against Cake 0.28.0

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/GenericIssueReportFixture.cs
- src/Cake.Issues.Reporting.Generic.Tests/packages.config
- src/Cake.Issues.Reporting.Generic/RazorEngineReferenceResolver.cs
Make Json.NET available in Razor templates
Fixes #33
> (GH-33) Make Json.NET available in Razor templates

- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/IIssueExtension.cs
- src/Cake.Issues.Reporting.Generic/RazorEngineReferenceResolver.cs
- src/Cake.Issues.Reporting.Generic/Templates/DataTable.cshtml
Add extension for returning file name and path
Fixes #37
> (GH-37) Add extension for returning file name and path

- src/Cake.Issues.Reporting.Generic.Tests/GenericIssueReportGeneratorTests.cs
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/GenericIssueReportTemplate.cs
- src/Cake.Issues.Reporting.Generic/GenericIssueReportTemplateExtensions.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Add report using DevExtreme DataGrid. See https://github.com/cake-contrib/Cake.Issues.Website/pull/57 for documentation.
Fixes #31
> (GH-31) Add report using DevExtreme DataGrid

- src/Cake.Issues.Reporting.Generic.Tests/GenericIssueReportGeneratorTests.cs
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/GenericIssueReportFormatSettings.cs
- src/Cake.Issues.Reporting.Generic/GenericIssueReportFormatSettingsExtensions.cs
- src/Cake.Issues.Reporting.Generic/GenericIssueReportGenerator.cs
- src/Cake.Issues.Reporting.Generic/RazorEngineReferenceResolver.cs
Add possibility to pass options to template which are available in the Razor ViewBag.
Fixes #17
> (GH-17) Add possibility to pass options to template

- src/Cake.Issues.Reporting.Generic/GenericIssueReportFormatAliases.cs
Add additional aliases for setting custom options
> (GH-17) Add additional aliases for setting custom options

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/ColumnSortOrderExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/DevExtremeThemeExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/GenericIssueReportFormatSettingsExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridTemplateTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/ViewBagHelperTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/packages.config
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/ColumnSortOrder.cs
- src/Cake.Issues.Reporting.Generic/ColumnSortOrderExtensions.cs
- src/Cake.Issues.Reporting.Generic/DevExtremeTheme.cs
- src/Cake.Issues.Reporting.Generic/DevExtremeThemeExtensions.cs
- src/Cake.Issues.Reporting.Generic/GenericIssueReportFormatSettingsExtensions.cs
- src/Cake.Issues.Reporting.Generic/GenericIssueReportTemplate.cs
- src/Cake.Issues.Reporting.Generic/GenericIssueReportTemplateExtensions.cs
- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/ReportColumn.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
- src/Cake.Issues.Reporting.Generic/ViewBagHelper.cs
Add options for DxDataGrid template
Fixes #41
> (GH-41) Add options for DxDataGrid template

- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Update HtmlDxDataGrid template to DevExteme 18.1.4
Fixes #39
> (GH-39) HtmlDxDataGrid: Update to DevExteme 18.1.4

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/FileLinkSettingsTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/UriExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/FileLinkSettings.cs
- src/Cake.Issues.Reporting.Generic/FileLinkType.cs
- src/Cake.Issues.Reporting.Generic/GenericIssueReportFormatAliases.cs
- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
- src/Cake.Issues.Reporting.Generic/UriExtensions.cs
Add possibility to link to a file
Fixes #47
> (GH-47) Add possibility to link to a file

- src/Cake.Issues.Reporting.Generic/GenericIssueReportFormatAliases.cs
Fix stack overflow exception in aliases
Fixes #50
> (GH-50) Fix aliases

- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
> Fix template formatting

- tools/packages.config
Build with Cake 0.29.0
Fixes #57
> (GH-57) Build with Cake 0.29.0

- src/Cake.Issues.Reporting.Generic.Tests/IIssueExtensionTests.cs
- src/Cake.Issues.Reporting.Generic/IIssueExtension.cs
Add missing tests for IIssueExtension
> Add missing tests for IIssueExtension

- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Add RuleUrl column. Hidden by default.
Fixes #68
> (GH-68) Add RuleUrl column

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/ExceptionAssertExtensions.cs
- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridColumnDescriptionTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridTemplateTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/IIssueExtensionTests.cs
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridColumnDescription.cs
- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/IIssueExtension.cs
- src/Cake.Issues.Reporting.Generic/ReportColumn.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
HtmlDxDataGrid: Add possibility to define additional columns
Fixes #44
> (GH-44) HtmlDxDataGrid: Add possibility to define additional columns

- src/Cake.Issues.Reporting.Generic.Tests/GenericIssueReportFixture.cs
- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridTemplateTests.cs
Add test cases for HtmlDxDataGridOption
>  Add test cases for HtmlDxDataGridOption 

- src/Cake.Issues.Reporting.Generic/Templates/DataTable.cshtml
Show only file in path column of HtmlDataTable template
Fixes #75
> (GH-75) Show only file in path column

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/packages.config
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/packages.config
Update to Cake.Issues 0.5.0-beta.2
Fixes #78
> (GH-78) Update to Cake.Issues 0.5.0

- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridTemplateTests.cs
- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/ReportColumn.cs
- src/Cake.Issues.Reporting.Generic/Templates/DataTable.cshtml
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Rename FilePath and File to FileDirectory and FileName
Fixes #79
> (GH-79) Rename FilePath and File to FileDirectory and FileName

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/packages.config
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/packages.config
Update to Cake.Issues 0.6.0 Beta 1
Fixes #84
> (GH-84) Update to Cake.Issues 0.6.0 Beta 1

- nuspec/nuget/Cake.Issues.Reporting.Generic.nuspec
Use jsDelivr for icon since RawGit is shutting down
> Use jsDelivr for icon

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/packages.config
> Update XUnit to 2.4.1

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/packages.config
> Update Shouldly to 3.0.2

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/app.config
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/packages.config
> Update FxCop analyzers

- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Update to DevExtreme 18.2.7
Fixes #92
> (GH-92) Update to DevExtreme 18.2.7

- src/Cake.Issues.Reporting.Generic.Tests/DevExtremeThemeExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridTemplateTests.cs
- src/Cake.Issues.Reporting.Generic/DevExtremeTheme.cs
- src/Cake.Issues.Reporting.Generic/DevExtremeThemeExtensions.cs
Add dark material theme to HtmlDxDataGrid template
Fixes #132
> (GH-132) Add dark material theme to HtmlDxDataGrid template

- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Add option to pass DevExtreme and jQuery location and version to HtmlDxDataGrid template
Fixes #55
> (GH-55) Add option to pass DevExtreme location to HtmlDxDataGrid template

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/packages.config
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/packages.config
Build against Cake 0.33.0
Fixes #146
> (GH-146) Build against Cake 0.33.0

- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/packages.config
Update FxCop Analyzers to 2.9.1
> Update FxCop Analyzers to 2.9.1

- setup.cake
- tools/packages.config
> Pin Cake.Recipe to 1.0.0

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/packages.config
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/packages.config
Update to Cake.Issues 0.7.0 Beta
Fixes #147
> (GH-147) Update to Cake.Issues 0.7.0

- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Update to DevExtreme 19.1
Fixes #167
> (GH-167) Update to DevExtreme 19.1

- src/Cake.Issues.Reporting.Generic.Tests/DevExtremeThemeExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridTemplateTests.cs
- src/Cake.Issues.Reporting.Generic/DevExtremeTheme.cs
- src/Cake.Issues.Reporting.Generic/DevExtremeThemeExtensions.cs
Add material compact themes for HtmlDxDataGrid template
Fixes #166
> (GH-166) HtmlDxDataGrid: Add material compact themes

- src/Cake.Issues.Reporting.Generic.Tests/DevExtremeThemeExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridTemplateTests.cs
Automatically test all DevExtreme themes
> Automatically test all DevExtreme themes

- src/Cake.Issues.Reporting.Generic/FileLinkSettings.cs
- src/Cake.Issues.Reporting.Generic/GenericIssueReportFormatAliases.cs
Alias for file link settings for Azure DevOps
Fixes #179
> (GH-179) Alias for file link settings for Azure DevOps

- README.md
- nuspec/nuget/Cake.Issues.Reporting.Generic.nuspec
Website changed to cakeissues.net
FIxes #192
> (GH-192) Change website to cakeissues.net

- docs/templates/htmldxdatagrid.md
Fix links to new repository and website URL
> Fix links to new repository and website URL

- docs/templates/htmldxdatagrid.md
Template can be used offline through options
> Template can be used offline through options

- demos/build/create-reports/create-reports-htmldxdatagrid-custom-export-filename.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-enable-exporting.cake
- demos/build/create-reports/create-reports-htmldxdatagrid.cake
- docs/templates/htmldxdatagrid-demo-customexportfilename.html
- docs/templates/htmldxdatagrid-demo-enableexporting.html
- docs/templates/htmldxdatagrid.md
- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridTemplateTests.cs
- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Add option to enable exporting of grid to Microsoft Excel to HtmlDxDataGrid template
Fixes #156
> (GH-156) HtmlDxDataGrid: Option to export grid to Microsoft Excel

- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridTemplateTests.cs
Improve test cases for HtmlDxDataGrid
> Improve test cases

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/GenericIssueReportGeneratorTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/IIssueExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridColumnDescription.cs
- src/Cake.Issues.Reporting.Generic/IIssueExtensions.cs
- src/Cake.Issues.Reporting.Generic/ReportColumn.cs
- src/Cake.Issues.Reporting.Generic/Templates/DataTable.cshtml
- src/Cake.Issues.Reporting.Generic/Templates/Diagnostic.cshtml
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Updates to Cake.Issues 0.8.0.
Fixes #215
> (GH-215) Update to Cake.Issues 0.8.0

- docs/examples/custom-template.md
- docs/features.md
Update documentation for 0.8.0 release
> Update documentation for 0.8.0

- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Update default version of DevExtreme to 19.2.3
Fixes #229 
Fixes #231
> (GH-229) Update DevExtreme to 19.2.3

- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Allow sorting by multiple columns at runtime
Fixes #232
> (GH-232) Allow sorting by multiple columns at runtime

- azure-pipelines.yml
- recipe.cake
Fix build by explicitely setting build configuration to Visual Studio 2019
> Build with Visual Studio 2019

- docs/templates/htmldxdatagrid-demo-customexportfilename.html
- docs/templates/htmldxdatagrid-demo-enableexporting.html
- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Update default version of JsZip to 3.2.2
Fixes #251
> (GH-251) Update JsZip to 3.2.2

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
Update to Cake.Issues 0.9.0
Fixes #271
> (GH-271) Update to Cake.Issues 0.9.0

- src/Cake.Issues.Reporting.Generic/Templates/DataTable.cshtml
- src/Cake.Issues.Reporting.Generic/Templates/Diagnostic.cshtml
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Originally part of #276, but can be merged independently
> Add missing usings to templates

- .appveyor.yml
- azure-pipelines.yml
- demos/build.cake
- demos/build/analyze/inspectcode.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-file-linking.cake
- demos/build/read-issues/read-issues.cake
- recipe.cake
Run demo generation as integration test
> Run demo generation as integration test

- build.ps1
- build.sh
Also bootstrap in build.sh file as it is done in build.ps1
> Bootstrap in build.sh

- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
Adds analyzers as private assets
> Add analyzers as private assets

- demos/build.cake
- demos/build/build/build.cake
- demos/build/read-issues/read-issues.cake
Use binary log file format for demos
> Use binary log file format for demo

- build.ps1
- build.sh
> (GH-297) Update to latest bootstrappers

- recipe.cake
Take package from for Cake.Recipe from Azure Artifacts instead of MyGet.
> Download Cake.Recipe from Azure Pipelines

- build.ps1
- build.sh
Fix bootstrapping in build script
> Fix bootstrapping in build script

- .gitignore
To ignore .DS_Store files which are created on Mac's
> (maint) Update .gitignore

- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Fix whitespace handling in DxDataGrid template
> Fix DxDataGrid template

- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Update DevExtreme to 20.1.6
Fixes #272
> (GH-272) Update DevExtreme to 20.1.6

- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Update jQuery to 3.50 in HtmlDxDataGrid template.
Fixes #273
> (GH-273) Update jQuery to 3.5.0

- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
Fix documentation for default value of DevExtremeVersion
> Fix documentation for default value of DevExtremeVersion

- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridTemplateTests.cs
- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Splits HtmlDxDataGridOption.JSZipLocation into location and version
Fixes #320
> (GH-320) Split HtmlDxDataGridOption.JSZipLocation into location and version

- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
> Fix jQuery default version

- src/Cake.Issues.Reporting.Generic/IIssueExtensions.cs
> Serialize URLs as string

- docs/templates/htmldatatable.md
- docs/templates/htmldxdatagrid.md
- src/Cake.Issues.Reporting.Generic.Tests/ExpandoObjectExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridTemplateTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/IIssueExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/IdeIntegrationSettingsTests.cs
- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/IIssueExtensions.cs
- src/Cake.Issues.Reporting.Generic/IdeIntegrationSettings.cs
- src/Cake.Issues.Reporting.Generic/ReportColumn.cs
- src/Cake.Issues.Reporting.Generic/Templates/DataTable.cshtml
- src/Cake.Issues.Reporting.Generic/Templates/Diagnostic.cshtml
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Add EndLine to templates
Fixes #277
> (GH-277) Add EndLine to templates

- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Use WithEnding extension to enforce trailing slash
> Use WithEnding extension to enforce trailing slash

- src/Cake.Issues.Reporting.Generic.Tests/ExpandoObjectExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/IIssueExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/IdeIntegrationSettingsTests.cs
- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/IIssueExtensions.cs
- src/Cake.Issues.Reporting.Generic/IdeIntegrationSettings.cs
- src/Cake.Issues.Reporting.Generic/ReportColumn.cs
- src/Cake.Issues.Reporting.Generic/Templates/Diagnostic.cshtml
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Add support for column information to default templates
Fixes #278
> (GH-278) Add support for column information

- demos/build.cake
- demos/build/analyze/analyze.cake
- demos/build/analyze/dupfinder.cake
- demos/build/analyze/inspectcode.cake
- demos/build/analyze/markdownlint.cake
- demos/src/ClassLibrary1/Class1.cs
> Add DupFinder to demos

- nuspec/nuget/Cake.Issues.Reporting.Generic.nuspec
Add XML documentation to NuGet package
> Add XML documentation to NuGet package

- recipe.cake
- tools/packages.config
Update to Cake.Recipe 2.0.0-alpha0487
> Update to Cake.Recipe 2.0.0-alpha0487

- recipe.cake
Update Cake.Recipe to 2.0.0 Alpha 493
> Update Cake.Recipe to 2.0.0 Alpha 493

- recipe.cake
Update to final version of Cake.Recipe 2.0
> Update to final version of Cake.Recipe 2.0

- recipe.cake
> Update Cake.Recipe to 2.1.0

- azure-pipelines.yml
- demos/.config/dotnet-tools.json
- demos/build.ps1
- demos/build.sh
- demos/tools/packages.config
> Update demos to Cake 1.0

- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
Migrate from FxCop analyzers to NETAnalyzers
> Migrate from FxCop analyzers to NETAnalyzers

- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
Build against Cake.Issues 1.0 Beta 1
Fixes #368
> (GH-368) Build against Cake.Issues 1.0 Beta 1

- recipe.cake
> Update Cake.Recipe to 2.2.0

- nuspec/nuget/Cake.Issues.Reporting.Generic.nuspec
Update NuGet package tags
Fixes #381
> (GH-381) Update NuGet package tags

- cake.config
Remove no longer required cake.config
> Remove no longer required cake.config

- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
> Improve XML comments

- src/Cake.Issues.Reporting.Generic/LitJson/JsonMapper.cs
- src/Cake.Issues.Reporting.Generic/LitJson/JsonWriter.cs
Update LitJson to 0.17.0
Fixes #400
> (GH-400) Update LitJson to 0.17.0

- docs/templates/htmldxdatagrid.md
Fix path to example source code
> Fix path to example source code

- docs/templates/htmldxdatagrid.md
Fix link to HtmlDxDataGridOption.EnableExporting setting
> Fix link to HtmlDxDataGridOption.EnableExporting setting

- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Update DevExtreme to 21.2.3. See [Release Notes](https://js.devexpress.com/New/21_2/) for details
Fixes #426
> (GH-426) Update DevExtreme to 21.2.3

- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Update jsPDF to 2.4.0
Fixes #433
> (GH-433) Update jsPDF to 2.4.0

- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Update jsPDF-AutoTable plugin to 3.5.22
Fixes #436
> (GH-436) Update jsPDF-AutoTable plugin to 3.5.22

- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Update ExcelJs to 4.3.2
Fixes #432
> (GH-432) Update ExcelJs to 4.3.2

- .github/dependabot.yml
- demos/frosting/build/Build.csproj
- demos/frosting/build/Program.cs
- demos/frosting/build/tasks/create-reports/CreateReportsHtmlDxDataGridGroupingTask.cs
- demos/frosting/build/tasks/create-reports/CreateReportsHtmlDxDataGridSortingTask.cs
- demos/script-runner/.config/dotnet-tools.json
- demos/script-runner/build/create-reports/create-reports-htmldxdatagrid-grouping.cake
- demos/script-runner/build/create-reports/create-reports-htmldxdatagrid-sorting.cake
- demos/script-runner/tools/packages.config
- docs/examples/custom-template.md
- docs/templates/htmldxdatagrid.md
- nuspec/nuget/Cake.Frosting.Issues.Reporting.Generic.nuspec
- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic.Tests/ExpandoObjectExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridTemplateTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/IIssueExtensionsTests.cs
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
- src/Cake.Issues.Reporting.Generic/IIssueExtensions.cs
- src/Cake.Issues.Reporting.Generic/ReportColumn.cs
- src/Cake.Issues.Reporting.Generic/Templates/DataTable.cshtml
- src/Cake.Issues.Reporting.Generic/Templates/Diagnostic.cshtml
- src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml
Updates to Cake 2.0 and Cake.Issues 2.0 Beta 1
Fixes #438
Fixes #425
> (GH-438) Update to Cake 2.0 and Cake.Issues 2.0 Beta 1

- nuspec/nuget/Cake.Frosting.Issues.Reporting.Generic.nuspec
Don't restrict running on Cake 1.x
Fixes #448
> (GH-448) Don't restrict running on Cake 1.x

- azure-pipelines.yml
Remove tests on macOS 10.15 and Ubuntu 18.04, add tests on macOS 11, macOS 13 and Ubuntu 22.04
> Update build images

- .vscode/settings.json
Adds settings for Visual Studio Code
> Add setting for Visual Studio Code

- src/Cake.Issues.Reporting.Generic/LitJson/IJsonWrapper.cs
- src/Cake.Issues.Reporting.Generic/LitJson/JsonData.cs
- src/Cake.Issues.Reporting.Generic/LitJson/JsonException.cs
- src/Cake.Issues.Reporting.Generic/LitJson/JsonMapper.cs
- src/Cake.Issues.Reporting.Generic/LitJson/JsonMockWrapper.cs
- src/Cake.Issues.Reporting.Generic/LitJson/JsonReader.cs
- src/Cake.Issues.Reporting.Generic/LitJson/JsonWriter.cs
- src/Cake.Issues.Reporting.Generic/LitJson/Lexer.cs
Updates LitJson to 0.18.0
Fixes #497
> Update LitJson to 0.18.0

- .github/renovate.json
Adds additional Renovate configuration for Cake Frosting addins
> Add Renovate configuration for Cake Frosting addins

- .appveyor.yml
- azure-pipelines.yml
- nuspec/nuget/Cake.Frosting.Issues.Reporting.Generic.nuspec
- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridColumnDescriptionTests.cs
- src/Cake.Issues.Reporting.Generic.Tests/HtmlDxDataGridTemplateTests.cs
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
- src/Cake.Issues.Reporting.Generic/ColumnSortOrderExtensions.cs
- src/Cake.Issues.Reporting.Generic/DevExtremeThemeExtensions.cs
- src/Cake.Issues.Reporting.Generic/GenericIssueReportFormatSettings.cs
- src/Cake.Issues.Reporting.Generic/GenericIssueReportTemplateExtensions.cs
- src/Cake.Issues.Reporting.Generic/StringExtensions.cs
- src/Directory.Build.props
Multi-Target .NET 6, .NET 7 & .NET 8
Fixes #547
> Multi-Target .NET 6, .NET 7 & .NET 8

- demos/frosting/global.json
- demos/script-runner/global.json
- global.json
> Add global.json

- nuspec/nuget/Cake.Frosting.Issues.Reporting.Generic.nuspec
- src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
- src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
Update Cake Issues to 4.0.0-beta0001
Fixes #549
> Update Cake Issues to 4.0.0-beta0001
