cake.config
setup.cake
tools/packages.config

Update to Cake 0.23.0 for compatibility with latest Cake.Recipe
Fixes #6

(GH-6) Upgrade to Cake 0.23.0

---

src/Cake.Issues.Reporting.Generic/RazorEngineReferenceResolver.cs

Loads `System.Core` which adds support for LINQ in templates back
Fixes #13

(GH-13) Add support for LINQ in templates

---

src/Cake.Issues.Reporting.Generic/Templates/DataTable.cshtml

Show `PriorityName` instead of `Priority` in DataTable template.
Fixes #22

(GH-22) Show PriorityName instead of Priority

---

src/Cake.Issues.Reporting.Generic/Templates/DataTable.cshtml

Show `ProviderName` instead of `ProviderType` in DataTable template.
Fixes #23

(GH-24) Show ProviderName instead of ProviderType

---

src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml

Hide RuleUrl column by default in HtmlDxDataGrid template
Fixes #73

(GH-73) Hide RuleUrl column by default

---

src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
src/Cake.Issues.Reporting.Generic.Tests/IdeIntegrationSettingsTests.cs
src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
src/Cake.Issues.Reporting.Generic/IdeIntegrationSettings.cs
src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml

Add IDE integration option. Currently only supported for HtmlDxDataGrid and TeamCityAddin
Fixes #49

(GH-49) Add IDE integration option

---

.appveyor.yml

Remove cache entry for AppVeyor which is no longer required since we now use global package folder

Remove cache entry for AppVeyor which is no longer required

---

src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml

Use HTML message if available for HtmlDxDataGrid template.
Fixes #217

 (GH-217) Support HTML for message 

---

docs/examples/custom-template.md
docs/examples/default-template.md

I think in example typo.
nuget package:"Cake.Issues.Reporting" and "Cake.Issues.Reporting.Generic"

Fix Example for Cake.Issues.Reporting

---

nuspec/nuget/Cake.Issues.Reporting.Generic.nuspec
src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
src/Cake.Issues.Reporting.Generic.Tests/Properties/AssemblyInfo.cs
src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj
src/Cake.Issues.Reporting.Generic/Properties/AssemblyInfo.cs

Regarding support for .NET Standard (#3)
Here's a multitarget build using the new project format, targeting:
- dotnet 4.6.1 (dotnetstandard2.0 compat)
- dotnet standard 2.0
- dotnet coreapp 2.0
These allow both frameworks to coexist, and coreapp is required to allow for testing in xUnit (can't use dotnetstandard2.0 in xUnit).  These target frameworks seem the most stable choice, but let me know if other targets are more appropriate.  
A few notes
- This will build and package, but won't "work" for dotnetcore - RazorEngine only supports the older framework.   Another PR will be needed to add another engine e.g. RazorLight with dotnetcore support.
- While xUnit tests "work", looks like it's only the first target they're testing.  This is somewhat advantageous, as tests would fail for …

Update to SDK style projecst

---

azure-pipelines.yml
demos/build.cake
demos/build.sh
recipe.cake

Use separate bootstrapping for building and testing to make it possible to use different versions of Cake or runners for tests which are not supported by build script yet.

Use separate bootstrapping for building and testing

---

.appveyor.yml
azure-pipelines.yml
demos/build.cake
demos/nuget.config
recipe.cake

Use #addin preprocessor directive for integration tests instead of referencing the assemblies directly. This allows future scenarios in the future (like e.g. multi-targeting)

Use #addin preprocessor directive for integration tests

---

nuspec/nuget/Cake.Frosting.Issues.Reporting.Generic.nuspec
nuspec/nuget/Cake.Issues.Reporting.Generic.nuspec
src/Cake.Issues.Reporting.Generic/GenericIssueReportFormatAliases.cs

Create specific addin for Cake Frosting which has dependencies defined instead of bundling required assemblies. 
Fixes #361

(GH-361) Create specific addin for Cake Frosting

---

src/Cake.Issues.Reporting.Generic/GenericIssueReportGenerator.cs

When running under Cake Frosting assembly for Linq is not loaded automatically. We therefore need to make sure that it is loaded and available for the templates when running in Cake Frosting.

Make sure assembly for Linq is loaded when running in Cake Frosting

---

azure-pipelines.yml

Run integration tests on Ubuntu 18.04 since Ubuntu 16.04 images are no longer available

Run integration tests on Ubuntu 18.04

---

.appveyor.yml
azure-pipelines.yml
nuspec/nuget/Cake.Frosting.Issues.Reporting.Generic.nuspec
nuspec/nuget/Cake.Issues.Reporting.Generic.nuspec
recipe.cake
src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj

Multi-Target .NET Core 3.1, 5, & 6 to follow best-practices for Cake 2.0.
Fixes #424

(GH-424) Multi-Target .NET Core 3.1, 5, & 6

---

README.md

Replace link to Gitter with GitHub Discussions
Fixes #357

(GH-357) Replace link to Gitter with GitHub Discussions

---

demos/script-runner/build.cake

Pin version of JetBrains tools, since DupFinder is no longer available in newer versions.

Pin version of JetBrains tools

---

.appveyor.yml
azure-pipelines.yml
demos/frosting/build/Build.csproj
demos/script-runner/.config/dotnet-tools.json
demos/script-runner/build/build/build.cake
demos/script-runner/tools/packages.config
nuspec/nuget/Cake.Frosting.Issues.Reporting.Generic.nuspec
src/Cake.Issues.Reporting.Generic.Tests/Cake.Issues.Reporting.Generic.Tests.csproj
src/Cake.Issues.Reporting.Generic/Cake.Issues.Reporting.Generic.csproj

Builds against Cake 3.0, Cake Issues 3.0 Beta 1 and updates target frameworks to .NET 6 and .NET 7.
Fixes #477
Fixes #478 
Fixes #479

Build against Cake 3.0 and update target frameworks

---

docs/templates/htmldxdatagrid-demo-exportformat-pdf.html
src/Cake.Issues.Reporting.Generic/HtmlDxDataGridOption.cs
src/Cake.Issues.Reporting.Generic/Templates/DxDataGrid.cshtml

Updates default version of jsPDF-AutoTable in HtmlDxDataGrid template to 3.5.29
Fixes #493

HtmlDxDataGrid: Update jsPDF-AutoTable to 3.5.29

---

src/Cake.Issues.Reporting.Generic.Tests/ExceptionAssertExtensions.cs
src/Cake.Issues.Reporting.Generic.Tests/IIssueExtensionsTests.cs

Use Shouldly everywhere for assertions. Fixes also wrong order of parameters passed to `Assert.Equal`.

Use Shouldly for assertions
